"""Generate a self-contained HTML mini-app with Grok."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Optional

from app.config import get_settings
from app.services import xai_client
from app.services.reply_app.intent import AppIntent


@dataclass
class GeneratedApp:
    title: str
    summary: str
    html: str
    model: str
    metadata: dict[str, Any]


_HTML_FENCE = re.compile(r"```(?:html)?\s*([\s\S]*?)```", re.I)


def _extract_html(content: str) -> str:
    content = (content or "").strip()
    m = _HTML_FENCE.search(content)
    if m:
        return m.group(1).strip()
    # bare document
    if "<html" in content.lower() or content.lstrip().startswith("<!DOCTYPE"):
        # strip leading junk before doctype/html
        lower = content.lower()
        idx = lower.find("<!doctype")
        if idx < 0:
            idx = lower.find("<html")
        if idx >= 0:
            return content[idx:].strip()
    return content


def _sanitize_html(html: str) -> str:
    """Light safety pass — not a full XSS auditor, just block obvious footguns."""
    # Remove script src= external (keep inline)
    html = re.sub(
        r"<script[^>]+src\s*=\s*[\"']https?://[^\"']+[\"'][^>]*>\s*</script>",
        "<!-- external script stripped -->",
        html,
        flags=re.I,
    )
    # Block javascript: URLs in href
    html = re.sub(r"""href\s*=\s*["']\s*javascript:""", 'href="#blocked"', html, flags=re.I)
    return html


def _fallback_html(title: str, brief: str) -> str:
    safe_title = title.replace("<", "")[:80]
    safe_brief = brief.replace("<", "")[:400]
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{safe_title}</title>
<style>
  :root {{ color-scheme: dark light; --bg:#0b0f14; --fg:#e8eef7; --muted:#8b9bb4; --card:#141b24; --accent:#7c5cff; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    background: radial-gradient(1200px 600px at 10% -10%, #1a1030, var(--bg)); color: var(--fg); min-height: 100vh; }}
  main {{ max-width: 520px; margin: 0 auto; padding: 24px 16px 48px; }}
  .card {{ background: var(--card); border: 1px solid #243041; border-radius: 16px; padding: 20px; }}
  h1 {{ font-size: 1.35rem; margin: 0 0 8px; }}
  p {{ color: var(--muted); line-height: 1.5; }}
  label {{ display:block; font-size: .85rem; margin: 14px 0 6px; color: var(--muted); }}
  input, textarea {{ width: 100%; padding: 12px 14px; border-radius: 10px; border: 1px solid #2c3a4f;
    background: #0d131c; color: var(--fg); font-size: 1rem; }}
  button {{ margin-top: 16px; width: 100%; padding: 12px 16px; border: 0; border-radius: 10px;
    background: linear-gradient(135deg, var(--accent), #4f8cff); color: white; font-weight: 600; font-size: 1rem; cursor: pointer; }}
  #out {{ margin-top: 16px; white-space: pre-wrap; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    background: #0d131c; border-radius: 10px; padding: 12px; min-height: 48px; border: 1px solid #2c3a4f; }}
  footer {{ margin-top: 18px; font-size: .75rem; color: var(--muted); text-align: center; }}
</style>
</head>
<body>
<main>
  <div class="card">
    <h1>{safe_title}</h1>
    <p>{safe_brief}</p>
    <label for="notes">Your input</label>
    <textarea id="notes" rows="4" placeholder="Type here…"></textarea>
    <button id="go" type="button">Run</button>
    <div id="out" aria-live="polite"></div>
  </div>
  <footer>Generated by Grok Reply App · runs fully in your browser</footer>
</main>
<script>
  const notes = document.getElementById('notes');
  const out = document.getElementById('out');
  document.getElementById('go').onclick = () => {{
    const v = (notes.value || '').trim();
    if (!v) {{ out.textContent = 'Add some input first.'; return; }}
    const lines = v.split(/\\n+/).map(s => s.trim()).filter(Boolean);
    out.textContent = 'Items: ' + lines.length + '\\n\\n' + lines.map((l,i) => (i+1) + '. ' + l).join('\\n');
    try {{ localStorage.setItem('replyapp-notes', v); }} catch (e) {{}}
  }};
  try {{
    const saved = localStorage.getItem('replyapp-notes');
    if (saved) notes.value = saved;
  }} catch (e) {{}}
</script>
</body>
</html>
"""


async def generate_html_app(intent: AppIntent) -> GeneratedApp:
    settings = get_settings()
    model = settings.xai_model
    system = (
        "You build tiny, beautiful, self-contained web apps as a SINGLE HTML document. "
        "Requirements:\n"
        "1. Return ONLY HTML (optional ```html fence). Start with <!DOCTYPE html>.\n"
        "2. Inline all CSS and JS. No build tools. Prefer zero external scripts.\n"
        "3. Mobile-first, works in X in-app browser, dark-friendly aesthetic.\n"
        "4. Actually interactive and useful for the brief — not a static landing page.\n"
        "5. Use localStorage when it helps. No backend calls, no API keys, no tracking.\n"
        "6. Accessible labels, large tap targets, clear primary action.\n"
        "7. Footer line: 'Generated by Grok Reply App'.\n"
        "8. Do not include markdown outside the HTML."
    )
    user = (
        f"Title: {intent.title}\n"
        f"Type: {intent.app_type}\n"
        f"Brief:\n{intent.brief}\n\n"
        "Build the complete app now."
    )

    try:
        content = await xai_client.chat_text(system, user, temperature=0.4)
        html = _sanitize_html(_extract_html(content))
        if "<html" not in html.lower():
            html = _fallback_html(intent.title, intent.brief)
            meta_note = "fallback_shell"
        else:
            meta_note = "grok_html"
        # Ensure doctype
        if not html.lstrip().lower().startswith("<!doctype"):
            html = "<!DOCTYPE html>\n" + html
    except Exception as e:
        html = _fallback_html(intent.title, intent.brief)
        meta_note = f"fallback_error:{e}"

    return GeneratedApp(
        title=intent.title,
        summary=intent.brief[:240],
        html=html,
        model=model,
        metadata={"generator": meta_note, "app_type": intent.app_type},
    )


async def maybe_preview_image(title: str, brief: str) -> Optional[bytes]:
    """Optional Imagine preview; returns PNG bytes or None."""
    settings = get_settings()
    if not settings.reply_app_attach_preview_image or not settings.xai_configured:
        return None
    prompt = (
        f"Clean mobile UI screenshot mockup of a minimal dark-mode web app titled '{title}'. "
        f"Purpose: {brief[:200]}. Flat product design, no real logos, no watermarks, "
        "centered phone frame, high contrast."
    )
    try:
        url = await xai_client.generate_image_url(prompt)
    except Exception:
        return None
    if not url:
        return None
    try:
        import httpx
        import base64

        if url.startswith("data:image"):
            # data:image/png;base64,...
            b64 = url.split(",", 1)[1]
            return base64.b64decode(b64)
        async with httpx.AsyncClient(timeout=60.0) as client:
            r = await client.get(url)
            r.raise_for_status()
            return r.content
    except Exception:
        return None
